package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CASE_ACTION_TAKEN.
 */
public class CaseActionTaken {

    private Long id;
    private String name;
    private Integer order;
    private Long case_id;

    public CaseActionTaken() {
    }

    public CaseActionTaken(Long id) {
        this.id = id;
    }

    public CaseActionTaken(Long id, String name, Integer order, Long case_id) {
        this.id = id;
        this.name = name;
        this.order = order;
        this.case_id = case_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getOrder() {
        return order;
    }

    public void setOrder(Integer order) {
        this.order = order;
    }

    public Long getCase_id() {
        return case_id;
    }

    public void setCase_id(Long case_id) {
        this.case_id = case_id;
    }

}
