package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CASE_IMAGE.
 */
public class CaseImage {

    private Long id;
    private String path;
    private Long case_id;

    public CaseImage() {
    }

    public CaseImage(Long id) {
        this.id = id;
    }

    public CaseImage(Long id, String path, Long case_id) {
        this.id = id;
        this.path = path;
        this.case_id = case_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Long getCase_id() {
        return case_id;
    }

    public void setCase_id(Long case_id) {
        this.case_id = case_id;
    }

}
