package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CASE_OBJ.
 */
public class CaseObj {

    private Long id;
    private Long dormitory_id;
    private Long block_id;
    private Long category_id;
    private Long case_status_id;
    private Long create_by;
    private Long assign_by;
    private Long assign_to;
    private String content;
    private String created_at;
    private String updated_at;
    private String spf_incident;
    private String case_investigation_name;
    private String case_investigation_contact;
    private String operative_remarks;
    private String government_agencies;
    private String head_ops_assessment;
    private String follow_up_timeline;
    private String assign_to_name;
    private String create_by_name;

    public CaseObj() {
    }

    public CaseObj(Long id) {
        this.id = id;
    }

    public CaseObj(Long id, Long dormitory_id, Long block_id, Long category_id, Long case_status_id, Long create_by, Long assign_by, Long assign_to, String content, String created_at, String updated_at, String spf_incident, String case_investigation_name, String case_investigation_contact, String operative_remarks, String government_agencies, String head_ops_assessment, String follow_up_timeline, String assign_to_name, String create_by_name) {
        this.id = id;
        this.dormitory_id = dormitory_id;
        this.block_id = block_id;
        this.category_id = category_id;
        this.case_status_id = case_status_id;
        this.create_by = create_by;
        this.assign_by = assign_by;
        this.assign_to = assign_to;
        this.content = content;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.spf_incident = spf_incident;
        this.case_investigation_name = case_investigation_name;
        this.case_investigation_contact = case_investigation_contact;
        this.operative_remarks = operative_remarks;
        this.government_agencies = government_agencies;
        this.head_ops_assessment = head_ops_assessment;
        this.follow_up_timeline = follow_up_timeline;
        this.assign_to_name = assign_to_name;
        this.create_by_name = create_by_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDormitory_id() {
        return dormitory_id;
    }

    public void setDormitory_id(Long dormitory_id) {
        this.dormitory_id = dormitory_id;
    }

    public Long getBlock_id() {
        return block_id;
    }

    public void setBlock_id(Long block_id) {
        this.block_id = block_id;
    }

    public Long getCategory_id() {
        return category_id;
    }

    public void setCategory_id(Long category_id) {
        this.category_id = category_id;
    }

    public Long getCase_status_id() {
        return case_status_id;
    }

    public void setCase_status_id(Long case_status_id) {
        this.case_status_id = case_status_id;
    }

    public Long getCreate_by() {
        return create_by;
    }

    public void setCreate_by(Long create_by) {
        this.create_by = create_by;
    }

    public Long getAssign_by() {
        return assign_by;
    }

    public void setAssign_by(Long assign_by) {
        this.assign_by = assign_by;
    }

    public Long getAssign_to() {
        return assign_to;
    }

    public void setAssign_to(Long assign_to) {
        this.assign_to = assign_to;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(String updated_at) {
        this.updated_at = updated_at;
    }

    public String getSpf_incident() {
        return spf_incident;
    }

    public void setSpf_incident(String spf_incident) {
        this.spf_incident = spf_incident;
    }

    public String getCase_investigation_name() {
        return case_investigation_name;
    }

    public void setCase_investigation_name(String case_investigation_name) {
        this.case_investigation_name = case_investigation_name;
    }

    public String getCase_investigation_contact() {
        return case_investigation_contact;
    }

    public void setCase_investigation_contact(String case_investigation_contact) {
        this.case_investigation_contact = case_investigation_contact;
    }

    public String getOperative_remarks() {
        return operative_remarks;
    }

    public void setOperative_remarks(String operative_remarks) {
        this.operative_remarks = operative_remarks;
    }

    public String getGovernment_agencies() {
        return government_agencies;
    }

    public void setGovernment_agencies(String government_agencies) {
        this.government_agencies = government_agencies;
    }

    public String getHead_ops_assessment() {
        return head_ops_assessment;
    }

    public void setHead_ops_assessment(String head_ops_assessment) {
        this.head_ops_assessment = head_ops_assessment;
    }

    public String getFollow_up_timeline() {
        return follow_up_timeline;
    }

    public void setFollow_up_timeline(String follow_up_timeline) {
        this.follow_up_timeline = follow_up_timeline;
    }

    public String getAssign_to_name() {
        return assign_to_name;
    }

    public void setAssign_to_name(String assign_to_name) {
        this.assign_to_name = assign_to_name;
    }

    public String getCreate_by_name() {
        return create_by_name;
    }

    public void setCreate_by_name(String create_by_name) {
        this.create_by_name = create_by_name;
    }

}
