package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CASE_SUB_CATEGORY.
 */
public class CaseSubCategory {

    private Long id;
    private String name;
    private String description;
    private Long case_id;

    public CaseSubCategory() {
    }

    public CaseSubCategory(Long id) {
        this.id = id;
    }

    public CaseSubCategory(Long id, String name, String description, Long case_id) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.case_id = case_id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Long getCase_id() {
        return case_id;
    }

    public void setCase_id(Long case_id) {
        this.case_id = case_id;
    }

}
