package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.DiaryVisitor;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table DIARY_VISITOR.
*/
public class DiaryVisitorDao extends AbstractDao<DiaryVisitor, Long> {

    public static final String TABLENAME = "DIARY_VISITOR";

    /**
     * Properties of entity DiaryVisitor.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "ID");
        public final static Property Diary_type_id = new Property(1, Long.class, "diary_type_id", false, "DIARY_TYPE_ID");
        public final static Property Is_staff = new Property(2, Integer.class, "is_staff", false, "IS_STAFF");
        public final static Property User_id = new Property(3, Long.class, "user_id", false, "USER_ID");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property Content = new Property(5, String.class, "content", false, "CONTENT");
        public final static Property Image_1 = new Property(6, String.class, "image_1", false, "IMAGE_1");
        public final static Property Image_2 = new Property(7, String.class, "image_2", false, "IMAGE_2");
        public final static Property Enter_time = new Property(8, String.class, "enter_time", false, "ENTER_TIME");
        public final static Property Exit_time = new Property(9, String.class, "exit_time", false, "EXIT_TIME");
        public final static Property Is_exited = new Property(10, Integer.class, "is_exited", false, "IS_EXITED");
        public final static Property Created_by = new Property(11, Long.class, "created_by", false, "CREATED_BY");
    };


    public DiaryVisitorDao(DaoConfig config) {
        super(config);
    }
    
    public DiaryVisitorDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'DIARY_VISITOR' (" + //
                "'ID' INTEGER PRIMARY KEY ," + // 0: id
                "'DIARY_TYPE_ID' INTEGER," + // 1: diary_type_id
                "'IS_STAFF' INTEGER," + // 2: is_staff
                "'USER_ID' INTEGER," + // 3: user_id
                "'NAME' TEXT," + // 4: name
                "'CONTENT' TEXT," + // 5: content
                "'IMAGE_1' TEXT," + // 6: image_1
                "'IMAGE_2' TEXT," + // 7: image_2
                "'ENTER_TIME' TEXT," + // 8: enter_time
                "'EXIT_TIME' TEXT," + // 9: exit_time
                "'IS_EXITED' INTEGER," + // 10: is_exited
                "'CREATED_BY' INTEGER);"); // 11: created_by
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'DIARY_VISITOR'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, DiaryVisitor entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long diary_type_id = entity.getDiary_type_id();
        if (diary_type_id != null) {
            stmt.bindLong(2, diary_type_id);
        }
 
        Integer is_staff = entity.getIs_staff();
        if (is_staff != null) {
            stmt.bindLong(3, is_staff);
        }
 
        Long user_id = entity.getUser_id();
        if (user_id != null) {
            stmt.bindLong(4, user_id);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(6, content);
        }
 
        String image_1 = entity.getImage_1();
        if (image_1 != null) {
            stmt.bindString(7, image_1);
        }
 
        String image_2 = entity.getImage_2();
        if (image_2 != null) {
            stmt.bindString(8, image_2);
        }
 
        String enter_time = entity.getEnter_time();
        if (enter_time != null) {
            stmt.bindString(9, enter_time);
        }
 
        String exit_time = entity.getExit_time();
        if (exit_time != null) {
            stmt.bindString(10, exit_time);
        }
 
        Integer is_exited = entity.getIs_exited();
        if (is_exited != null) {
            stmt.bindLong(11, is_exited);
        }
 
        Long created_by = entity.getCreated_by();
        if (created_by != null) {
            stmt.bindLong(12, created_by);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public DiaryVisitor readEntity(Cursor cursor, int offset) {
        DiaryVisitor entity = new DiaryVisitor( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // diary_type_id
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // is_staff
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // user_id
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // content
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // image_1
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // image_2
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // enter_time
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // exit_time
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // is_exited
            cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11) // created_by
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, DiaryVisitor entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDiary_type_id(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setIs_staff(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setUser_id(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setContent(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setImage_1(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setImage_2(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setEnter_time(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setExit_time(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setIs_exited(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setCreated_by(cursor.isNull(offset + 11) ? null : cursor.getLong(offset + 11));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(DiaryVisitor entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(DiaryVisitor entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
