package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DIARY_OTHER.
 */
public class DiaryOther {

    private Long id;
    private Long diary_type_id;
    private String content;
    private Long created_by;
    private String created_at;
    private Long status;
    private String created_by_name;

    public DiaryOther() {
    }

    public DiaryOther(Long id) {
        this.id = id;
    }

    public DiaryOther(Long id, Long diary_type_id, String content, Long created_by, String created_at, Long status, String created_by_name) {
        this.id = id;
        this.diary_type_id = diary_type_id;
        this.content = content;
        this.created_by = created_by;
        this.created_at = created_at;
        this.status = status;
        this.created_by_name = created_by_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDiary_type_id() {
        return diary_type_id;
    }

    public void setDiary_type_id(Long diary_type_id) {
        this.diary_type_id = diary_type_id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public Long getCreated_by() {
        return created_by;
    }

    public void setCreated_by(Long created_by) {
        this.created_by = created_by;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public Long getStatus() {
        return status;
    }

    public void setStatus(Long status) {
        this.status = status;
    }

    public String getCreated_by_name() {
        return created_by_name;
    }

    public void setCreated_by_name(String created_by_name) {
        this.created_by_name = created_by_name;
    }

}
