package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DIARY_VISITOR.
 */
public class DiaryVisitor {

    private Long id;
    private Long diary_type_id;
    private Integer is_staff;
    private Long user_id;
    private String name;
    private String content;
    private String image_1;
    private String image_2;
    private String enter_time;
    private String exit_time;
    private Integer is_exited;
    private Long created_by;

    public DiaryVisitor() {
    }

    public DiaryVisitor(Long id) {
        this.id = id;
    }

    public DiaryVisitor(Long id, Long diary_type_id, Integer is_staff, Long user_id, String name, String content, String image_1, String image_2, String enter_time, String exit_time, Integer is_exited, Long created_by) {
        this.id = id;
        this.diary_type_id = diary_type_id;
        this.is_staff = is_staff;
        this.user_id = user_id;
        this.name = name;
        this.content = content;
        this.image_1 = image_1;
        this.image_2 = image_2;
        this.enter_time = enter_time;
        this.exit_time = exit_time;
        this.is_exited = is_exited;
        this.created_by = created_by;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDiary_type_id() {
        return diary_type_id;
    }

    public void setDiary_type_id(Long diary_type_id) {
        this.diary_type_id = diary_type_id;
    }

    public Integer getIs_staff() {
        return is_staff;
    }

    public void setIs_staff(Integer is_staff) {
        this.is_staff = is_staff;
    }

    public Long getUser_id() {
        return user_id;
    }

    public void setUser_id(Long user_id) {
        this.user_id = user_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getImage_1() {
        return image_1;
    }

    public void setImage_1(String image_1) {
        this.image_1 = image_1;
    }

    public String getImage_2() {
        return image_2;
    }

    public void setImage_2(String image_2) {
        this.image_2 = image_2;
    }

    public String getEnter_time() {
        return enter_time;
    }

    public void setEnter_time(String enter_time) {
        this.enter_time = enter_time;
    }

    public String getExit_time() {
        return exit_time;
    }

    public void setExit_time(String exit_time) {
        this.exit_time = exit_time;
    }

    public Integer getIs_exited() {
        return is_exited;
    }

    public void setIs_exited(Integer is_exited) {
        this.is_exited = is_exited;
    }

    public Long getCreated_by() {
        return created_by;
    }

    public void setCreated_by(Long created_by) {
        this.created_by = created_by;
    }

}
