package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DIARY_ALL.
 */
public class DiaryAll {

    private Long id;
    private Long diary_type_id;
    private String content;
    private String created_at;
    private String created_by_name;

    public DiaryAll() {
    }

    public DiaryAll(Long id) {
        this.id = id;
    }

    public DiaryAll(Long id, Long diary_type_id, String content, String created_at, String created_by_name) {
        this.id = id;
        this.diary_type_id = diary_type_id;
        this.content = content;
        this.created_at = created_at;
        this.created_by_name = created_by_name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getDiary_type_id() {
        return diary_type_id;
    }

    public void setDiary_type_id(Long diary_type_id) {
        this.diary_type_id = diary_type_id;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getCreated_by_name() {
        return created_by_name;
    }

    public void setCreated_by_name(String created_by_name) {
        this.created_by_name = created_by_name;
    }

}
