package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table LEVEL.
 */
public class Level {

    private Long id;
    private Integer block_id;
    private String name;

    public Level() {
    }

    public Level(Long id) {
        this.id = id;
    }

    public Level(Long id, Integer block_id, String name) {
        this.id = id;
        this.block_id = block_id;
        this.name = name;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getBlock_id() {
        return block_id;
    }

    public void setBlock_id(Integer block_id) {
        this.block_id = block_id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
