package greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table WORKER.
 */
public class Worker {

    private Long id;
    private String barcode;
    private String name;
    private String nationality_code;
    private String passport;
    private String expiry;
    private Integer sex;
    private String company;
    private String work_permit;
    private Long dormitory_id;
    private Long block_id;
    private Long level_id;
    private Long room_id;
    private String unit_number;
    private String image_1;
    private String image_2;
    private String image_3;
    private String created_at;
    private String updated_at;
    private String log_message;

    public Worker() {
    }

    public Worker(Long id) {
        this.id = id;
    }

    public Worker(Long id, String barcode, String name, String nationality_code, String passport, String expiry, Integer sex, String company, String work_permit, Long dormitory_id, Long block_id, Long level_id, Long room_id, String unit_number, String image_1, String image_2, String image_3, String created_at, String updated_at, String log_message) {
        this.id = id;
        this.barcode = barcode;
        this.name = name;
        this.nationality_code = nationality_code;
        this.passport = passport;
        this.expiry = expiry;
        this.sex = sex;
        this.company = company;
        this.work_permit = work_permit;
        this.dormitory_id = dormitory_id;
        this.block_id = block_id;
        this.level_id = level_id;
        this.room_id = room_id;
        this.unit_number = unit_number;
        this.image_1 = image_1;
        this.image_2 = image_2;
        this.image_3 = image_3;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.log_message = log_message;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getBarcode() {
        return barcode;
    }

    public void setBarcode(String barcode) {
        this.barcode = barcode;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getNationality_code() {
        return nationality_code;
    }

    public void setNationality_code(String nationality_code) {
        this.nationality_code = nationality_code;
    }

    public String getPassport() {
        return passport;
    }

    public void setPassport(String passport) {
        this.passport = passport;
    }

    public String getExpiry() {
        return expiry;
    }

    public void setExpiry(String expiry) {
        this.expiry = expiry;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public String getCompany() {
        return company;
    }

    public void setCompany(String company) {
        this.company = company;
    }

    public String getWork_permit() {
        return work_permit;
    }

    public void setWork_permit(String work_permit) {
        this.work_permit = work_permit;
    }

    public Long getDormitory_id() {
        return dormitory_id;
    }

    public void setDormitory_id(Long dormitory_id) {
        this.dormitory_id = dormitory_id;
    }

    public Long getBlock_id() {
        return block_id;
    }

    public void setBlock_id(Long block_id) {
        this.block_id = block_id;
    }

    public Long getLevel_id() {
        return level_id;
    }

    public void setLevel_id(Long level_id) {
        this.level_id = level_id;
    }

    public Long getRoom_id() {
        return room_id;
    }

    public void setRoom_id(Long room_id) {
        this.room_id = room_id;
    }

    public String getUnit_number() {
        return unit_number;
    }

    public void setUnit_number(String unit_number) {
        this.unit_number = unit_number;
    }

    public String getImage_1() {
        return image_1;
    }

    public void setImage_1(String image_1) {
        this.image_1 = image_1;
    }

    public String getImage_2() {
        return image_2;
    }

    public void setImage_2(String image_2) {
        this.image_2 = image_2;
    }

    public String getImage_3() {
        return image_3;
    }

    public void setImage_3(String image_3) {
        this.image_3 = image_3;
    }

    public String getCreated_at() {
        return created_at;
    }

    public void setCreated_at(String created_at) {
        this.created_at = created_at;
    }

    public String getUpdated_at() {
        return updated_at;
    }

    public void setUpdated_at(String updated_at) {
        this.updated_at = updated_at;
    }

    public String getLog_message() {
        return log_message;
    }

    public void setLog_message(String log_message) {
        this.log_message = log_message;
    }

}
